name: just_audio
description: Audio player for files, assets, URLs and DASH/HLS streams supporting gapless looping, shuffling, concatenating, clipping. Works with audio_service to play audio in the background.
version: 0.7.0-nullsafety.0
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  just_audio_platform_interface: ^3.0.0-nullsafety.0
  just_audio_web: ^0.3.0-nullsafety.0
  audio_session: ^0.1.0-nullsafety.3
  rxdart: ^0.26.0-nullsafety.1
  path: ^1.8.0-nullsafety.3
  #path_provider: ^1.6.10
  async: ^2.5.0-nullsafety.3
  uuid: ^3.0.0-nullsafety.0
  crypto: ^3.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.5
  plugin_platform_interface: ^1.1.0-nullsafety.1

dependency_overrides:
  crypto: ^3.0.0-nullsafety.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
      macos:
        pluginClass: JustAudioPlugin
      web:
        default_package: just_audio_web
