name: just_audio_background
description: Background implementation of just_audio
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_background
version: 0.0.1

# flutter:
#   plugin:
#     platforms:
#       # web:
#       #   pluginClass: JustAudioBackgroundPlugin
#       #   fileName: just_audio_background_plugin.dart

dependencies:
  #just_audio_platform_interface: ^3.0.0
  just_audio_platform_interface:
    path: ../just_audio_platform_interface
  audio_service:
    git:
      url: https://github.com/ryanheise/audio_service.git
      ref: d83855dd6eee
      path: audio_service
  audio_session: ^0.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  rxdart: ^0.26.0

dev_dependencies:
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
