name: just_audio_platform_interface
description: A common platform interface for the just_audio plugin.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 3.0.0-nullsafety.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.1.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.5
  pedantic: ^1.10.0-nullsafety.3

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.5"
