name: just_audio_example
description: Demonstrates how to use the just_audio plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.0-nullsafety.3
  just_audio:
    path: ../

dev_dependencies:
  # TODO: uncomment these dependencies when they have nullsafe versions.
  # flutter_driver:
  #   sdk: flutter
  flutter_test:
    sdk: flutter
  # integration_test: ^1.0.1
  test:

flutter:
  uses-material-design: true

  assets:
    - audio/
